// <auto-generated />
using System;
using Maliev.ReceiptService.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.ReceiptService.Data.Migrations
{
    [DbContext(typeof(ReceiptDbContext))]
    [Migration("20251217164541_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.ReceiptService.Data.Models.Entities.InvoiceBalanceTracker", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("remaining_balance");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<decimal>("TotalInvoiceAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_invoice_amount");

                    b.Property<decimal>("TotalReceiptedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_receipted_amount");

                    b.HasKey("InvoiceId", "SegmentId")
                        .HasName("pk_invoice_balance_trackers");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_balance_trackers_invoice_id");

                    b.HasIndex("RemainingBalance")
                        .HasDatabaseName("ix_invoice_balance_trackers_remaining_balance");

                    b.ToTable("invoice_balance_trackers");
                });

            modelBuilder.Entity("Maliev.ReceiptService.Data.Models.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_address");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerTaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_tax_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("InvoiceSegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_segment_id");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<Guid?>("PdfReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("pdf_reference_id");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receipt_number");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("void_reason");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<string>("VoidedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voided_by");

                    b.Property<decimal?>("WithholdingTaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("withholding_tax_amount");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_receipts_created_at");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_receipts_invoice_id");

                    b.HasIndex("IssueDate")
                        .HasDatabaseName("ix_receipts_issue_date");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_receipts_receipt_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_receipts_status");

                    b.ToTable("receipts");
                });

            modelBuilder.Entity("Maliev.ReceiptService.Data.Models.Entities.ReceiptAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_state");

                    b.Property<string>("PreviousState")
                        .HasColumnType("text")
                        .HasColumnName("previous_state");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<DateTime>("RetainUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retain_until");

                    b.Property<string>("StaffMemberId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("staff_member_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_receipt_audit_events");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_receipt_audit_events_event_type");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_receipt_audit_events_receipt_id");

                    b.HasIndex("RetainUntil")
                        .HasDatabaseName("ix_receipt_audit_events_retain_until");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_receipt_audit_events_timestamp");

                    b.ToTable("receipt_audit_events");
                });

            modelBuilder.Entity("Maliev.ReceiptService.Data.Models.Entities.ReceiptLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("InvoiceLineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_line_item_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_receipt_line_items");

                    b.HasIndex("InvoiceLineItemId")
                        .HasDatabaseName("ix_receipt_line_items_invoice_line_item_id");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_receipt_line_items_receipt_id");

                    b.ToTable("receipt_line_items");
                });

            modelBuilder.Entity("Maliev.ReceiptService.Data.Models.Entities.ReceiptAuditEvent", b =>
                {
                    b.HasOne("Maliev.ReceiptService.Data.Models.Entities.Receipt", "Receipt")
                        .WithMany("AuditEvents")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_audit_events_receipts_receipt_id");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Maliev.ReceiptService.Data.Models.Entities.ReceiptLineItem", b =>
                {
                    b.HasOne("Maliev.ReceiptService.Data.Models.Entities.Receipt", "Receipt")
                        .WithMany("LineItems")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_line_items_receipts_receipt_id");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Maliev.ReceiptService.Data.Models.Entities.Receipt", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
